version: '3.8'

services:
  api:
    container_name: task-manager-api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3000}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_DATABASE=${DB_DATABASE:-task_manager}
      - DB_SYNC=true
      - JWT_SECRET=${JWT_SECRET:-your_secret_key_change_in_production}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-1d}
    networks:
      - task-manager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 30s

  postgres:
    container_name: task-manager-postgres
    image: postgres:14-alpine
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_DB=${DB_DATABASE:-task_manager}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-manager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Servicio para pgAdmin (opcional)
  pgadmin:
    container_name: task-manager-pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "${PGADMIN_PORT:-5050}:5050"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - task-manager-network
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  task-manager-network:
    driver: bridge